version: '3.8'
services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    pid: host
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    ports:
      - 9187:9187
    environment:
      - DATA_SOURCE_URI=postgres:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5433:5432 # Map host port 5433 to container port 5432 (default for postgres)
    environment:
      - POSTGRES_PASSWORD=postgres # Set password for postgres user (replace with desired password)
      - POSTGRES_USER=postgres # Default postgres user
      - POSTGRES_DB=postgres # Default postgres database
    volumes:
      - postgres_data:/var/lib/postgresql/data

  apix:
    image: dotnetapi:latest
    container_name: apix
    ports:
      - 5045:5045
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    
volumes:
  grafana:
  postgres_data:
